# Generated by Django 5.1.7 on 2025-04-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('faculty_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
                ('kafedra_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.group')),
                ('class_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
    ]
