# Generated by Django 5.2 on 2025-04-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_subject_group_faculty_student_age_student_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
