# Generated by Django 5.2 on 2025-04-13 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='kafedra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.kafedra'),
            preserve_default=False,
        ),
    ]
